### ISSUE TITLE
ZoomSurfaceView : java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by narcdev** [natario1/ZoomLayout#143]
Hi

I'm trying to play with your awesome library and I have something "strange".

Please find here the the crash message
```
java.lang.NoSuchMethodError: No direct method <init>(IILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/otaliastudios/opengl/program/GlTextureProgram; or its super classes (declaration of 'com.otaliastudios.opengl.program.GlTextureProgram')
```

My res file
```
    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <com.otaliastudios.zoom.ZoomSurfaceView
            android:id="@+id/surfaceView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:horizontalPanEnabled="true"
            app:verticalPanEnabled="true"
            app:zoomEnabled="true" />
    </FrameLayout>
```

And the config in my build.gradle
```
    implementation 'com.otaliastudios.opengl:egloo:0.4.0'
    implementation 'com.otaliastudios:zoomlayout:1.7.0'
```
######################################################################
BUT, if I include the previous version of egloo :
```
    implementation 'com.otaliastudios.opengl:egloo:0.3.1'
    implementation 'com.otaliastudios:zoomlayout:1.7.0'
```

Everything is OK and no crash appear..

Thanks in advance and keep going your awesome work !

**Comment by natario1** [comment]
ZL 1.7.0 works with Egloo 0.2.3 so you should not udpate that.
Starting from ZL 1.7.1, which was just released, you can actually remove the egloo dependency!
